services:
  api:
    container_name: my-greatest-api
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - ENV=local

  db:
    image: postgres:16.4-alpine # latest v16 on 2024-10-12
    container_name: my-greatest-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=myrole
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
