name: CI-backend

on:
  push:
    branches: 
      - main

  pull_request:
    branches:
      - main
    paths:
      - .python-version
      - pyproject.toml
      - uv.lock
      - app/**/*.py

env:
  ENV: local


jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --all-extras --dev
      
      - name: Lint
        run: uv run ruff format --check --diff app/

  unittest:
    name: Unit test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16.4-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: myrole
          POSTGRES_PASSWORD: mypassword
          POSTGRES_DB: mydb

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --all-extras --dev
      
      - name: Unittest
        run: uv run pytest app/
